import Head from "next/head";
import Hero from "@/components/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Renato Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10">
        <Hero />
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the beginning of my journey as a Freelancer lalala
              sjjdkajsdk alksaksa. So alsadljjsad aosjdjsado ojasojdsd.
              <span className=" text-teal-500">agencies </span> consulted for{" "}
              <span className=" text-teal-500"> startups</span> and colaboredete
              sfor asjjos amsmaksdj and so forth.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the beginning of my journey as a Freelancer lalala
              sjjdkajsdk alksaksa. So alsadljjsad aosjdjsado ojasojdsd.
              <span className=" text-teal-500">agencies </span> consulted for{" "}
              <span className=" text-teal-500"> startups</span> and colaboredete
              sfor asjjos amsmaksdj and so forth.
            </p>
          </div>
        </section>
      </main>
    </>
  );
}
