import Head from "next/head";
import Hero from "@/sections/Hero";
import Portfolio from "@/sections/Portfolio";
import About from "@/sections/About";
import Skills from "@/sections/Skills";
import Qualifications from "@/sections/Qualifications";


export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Renato Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <Hero />
        <About />
        <Skills />
        <Qualifications />
        <Portfolio />
      </main>
    </div>
  );
}
