import Head from "next/head";
import Hero from "@/components/Hero";
import Projects from '@/components/Projects'
import Portfolio from "@/components/Portfolio";


export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Renato Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <Hero />
        <Projects />
        <Portfolio />
        
      </main>
    </div>
  );
}
